services:
  postgres:
    image: postgres:latest
    container_name: market-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - market-net

volumes:
  pgdata:

networks:
  market-net:
    driver: bridge
